<?php
include_once '../../../includes/services.php';
$codigoRecaudacion = isset($_GET['codigo']) ? $_GET['codigo'] : null;
$servicios = new servicios();
$data = $servicios->BuscarRecaudacionPorCodigo($codigoRecaudacion);
//var_dump($data);exit;
?>




<div class="box">

    <div class="box-body table-responsive">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Codigo</th>
                    <th>numeroSerie</th>
                    <th>numeroBoleta</th>
                    <th>subtotal</th>
                    <th>igv</th>
                    <th>total</th>
                    <th>Agregar</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $ListarOrdenesCliente = $servicios->ListarBoletasNuevasPorCodigoContrato($_GET['codigo']);
                if ($ListarOrdenesCliente) {
                    foreach ($ListarOrdenesCliente as $indice => $registro) {
                        ?>
                        <tr>
                            <td><?php echo $registro['codigo'] ?></td>
                            <td><?php echo $registro['numeroSerie'] ?></td>
                            <td><?php echo $registro['numeroBoleta'] ?></td>
                            <td><?php echo $registro['subtotal'] ?></td>
                            <td><?php echo $registro['igv'] ?></td>
                            <td><?php echo $registro['total'] ?></td>
                            <td onclick="comprueba(this)"><a href="javascript:void(0)"  onclick="$('#codigoBoleta').val(<?php echo $registro['codigo'] ?>);"><i class="fa fa-plus-square"></i></a></td>
                           <!--<td> <button type="button" class="btn  btn-default btn-flat" data-toggle="modal"  data-target="#myModal" href="#" id="<?php echo $registro['codigo'] ?>"><i class="fa fa-plus-square"></i></button></td>-->
                        </tr>
                        <?php
                    }}
                    ?>
                </tbody>
            </table>
        </div> 
    </div>  
    <?php if ($ListarOrdenesCliente) { ?>
<div>
        <form  method="post" id="form1" action="controllers/registrar-recaudacion-insertar.php"  name="form1" style="display:none" role="form"  >
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Fecha de Recaudación</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>

                        <input class="form-control" value="" name="fechaRecaudacion" type="text" data-mask="" data-inputmask="'alias': 'dd/mm/yyyy'">
                    </div>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label for="tipoCambio">Tipo de Cambio</label>
                    <input type="hidden" id="codigoBoleta" name="codigoBoleta" value="" />
                    <input type="hidden" id="T_Contrato_codigo" name="T_Contrato_codigo" value="<?php echo $_GET['codigo']?>" />
                    <input type="hidden"  name="codigoRecaudacion"   value='0' >
                    <input type="text"  name="tipoCambio"   value='' class="form-control"  placeholder="Tipo de cambio">
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Banco</label>
                    <select name="T_CobranzaBanco" class="form-control">
                        <option value='0'>Selecciona Opci&oacute;n...</option> 
                        <?php
                        $Bancos = $servicios->ListarBancos();
                        foreach ($Bancos as $indice => $registro) {
                            echo "<option value='" . (int) $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label>Estado Boleta</label>
                    <select name="estadoComprobante" class="form-control">
                        <option value='0'>Selecciona Opci&oacute;n...</option> 
                        <?php
                        $EstadosComprobante = $servicios->ListarEstadosComprobante();
                        foreach ($EstadosComprobante as $indice => $registro) {
                            echo "<option value='" . (int) $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>
</div>
    <?php } else {
        ?>
        <div class="alert alert-info alert-dismissable">
            <i class="fa fa-info"/>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b>Alerta!</b>
            No hay boletas pendientes.
        </div>
    <?php }
    ?>

<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>

<script type="text/javascript">
    
    function comprueba(objOrigen) {
    document.getElementById("form1").style.display = "block";
}
                        $(function () {
                            //Datemask dd/mm/yyyy
                            $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
                            //Datemask2 mm/dd/yyyy
                            $("#datemask2").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
                            //Money Euro
                            $("[data-mask]").inputmask();

                            //Date range picker
                            $('#reservation').daterangepicker();
                            //Date range picker with time picker
                            $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
                            //Date range as a button
                            $('#daterange-btn').daterangepicker(
                                    {
                                        ranges: {
                                            'Today': [moment(), moment()],
                                            'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                                            'Last 7 Days': [moment().subtract('days', 6), moment()],
                                            'Last 30 Days': [moment().subtract('days', 29), moment()],
                                            'This Month': [moment().startOf('month'), moment().endOf('month')],
                                            'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                                        },
                                        startDate: moment().subtract('days', 29),
                                        endDate: moment()
                                    },
                            function (start, end) {
                                $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                            }
                            );

                            //iCheck for checkbox and radio inputs
                            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                                checkboxClass: 'icheckbox_minimal',
                                radioClass: 'iradio_minimal'
                            });
                            //Red color scheme for iCheck
                            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                                checkboxClass: 'icheckbox_minimal-red',
                                radioClass: 'iradio_minimal-red'
                            });
                            //Flat red color scheme for iCheck
                            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                                checkboxClass: 'icheckbox_flat-red',
                                radioClass: 'iradio_flat-red'
                            });

                            //Colorpicker
                            $(".my-colorpicker1").colorpicker();
                            //color picker with addon
                            $(".my-colorpicker2").colorpicker();

                            //Timepicker
                            $(".timepicker").timepicker({
                                showInputs: false
                            });
                        });


                        $(document).ready(function () {
                            $('#vinculo').click(function () {
                                $valor = $(this).attr('parametro'); // puedes remplazar "parametro" por le parametro que desees ya sea standar o personalizado
                                $('#codigoBoleta').val($valor);
                                
                            });
                        });

</script>
