<?php
include_once '../../../includes/services.php';
$codigoRecaudacion = isset($_GET['codigo']) ? $_GET['codigo'] : null;
$servicios = new servicios();
$data = $servicios->BuscarRecaudacionPorCodigo($codigoRecaudacion);
?>
<div class="box">
    <div class="box-body">
        <div class="row">
            <label class="col-xs-3 control-label">mesBoleta</label>
            <div class="col-xs-3">
                <input type="text" value="<?php
                $mesBoleta = date_create($data['mesBoleta']);
                echo date_format($mesBoleta, 'd/m/Y')
                ?> " class="form-control" placeholder="mesBoleta" disabled>
            </div>
            <label class="col-xs-3 control-label">fechaEmision</label>
            <div class="col-xs-3">
                <input type="text"  value="<?php
                       $fechaEmision = date_create($data['fechaEmision']);
                       echo date_format($fechaEmision, 'd/m/Y')
                       ?>" class="form-control" placeholder="fechaEmision" disabled>
            </div>

        </div>
    </div> 

    <div class="box-body">
        <div class="row">
            <label class="col-xs-2 control-label">subtotal</label>
            <div class="col-xs-2">
                <input type="text" value="<?php echo $data["subtotal"] ?>" class="form-control" placeholder="subtotal" disabled>
            </div>
            <label class="col-xs-2 control-label">Igv</label>
            <div class="col-xs-2">
                <input type="text"  value="<?php echo $data["igv"] ?>" class="form-control" placeholder="igv" disabled>
            </div>
            <label class="col-xs-2 control-label">Total</label>
            <div class="col-xs-2">
                <input type="text"  value="<?php echo $data["total"] ?>" class="form-control" placeholder="total" disabled>
            </div>
        </div>
    </div>
</div>
<form  method="post" action="controllers/registrar-recaudacion.php"  name="registration_form" role="form" >
    <div class="col-xs-6">
        <div class="form-group">
            <label>Fecha de Recaudación</label>
            <div class="input-group">
                <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                </div>
         
                <input class="form-control" value="<?php 
                       $fechaRecaudacion = date_create($data['fechaRecaudacion']);
                       echo date_format($fechaRecaudacion, 'd/m/Y')
                       ?>" name="fechaRecaudacion" type="text" data-mask="" data-inputmask="'alias': 'dd/mm/yyyy'">
            </div>
        </div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">
            <label for="tipoCambio">Tipo de Cambio</label>
            <input type="hidden"  name="codigoBoleta"   value='<?php echo (int) $data["codigoBoleta"] ?>' >
            <input type="hidden"  name="codigoRecaudacion"   value='<?php echo (int) $data["codigoRecaudacion"] ?>' >
            <input type="hidden"  name="T_Contrato_codigo"   value='<?php echo (int) $data["T_Contrato_codigo"] ?>' >
            <input type="hidden"  name="T_FacturacionBoleta_codigo"   value='<?php echo (int) $data["T_FacturacionBoleta_codigo"] ?>' >
            <input type="hidden"  name="T_FacturacionBoleta_numeroSerie"   value='<?php echo $data["T_FacturacionBoleta_numeroSerie"] ?>' >
            <input type="hidden"  name="T_FacturacionBoleta_numeroBoleta"   value='<?php echo $data["T_FacturacionBoleta_numeroBoleta"] ?>' >
            <input type="text"  name="tipoCambio"   value='<?php echo $data["tipoCambio"] ?>' class="form-control"  placeholder="Tipo de cambio">
        </div>
    </div>
    <div class="col-xs-6">
        <div class="form-group">
            <label>Banco</label>
            <select name="T_CobranzaBanco" class="form-control">
                <option value='0'>Selecciona Opci&oacute;n...</option> 
                <?php
                $Bancos = $servicios->ListarBancos();
                foreach ($Bancos as $indice => $registro) {
                    if ($registro['codigo'] == $data['T_CobranzaBanco']) {
                        echo "<option selected='" . (int) $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                    } else {
                        echo "<option value='" . (int) $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                    }
                }
                ?>
            </select>
        </div></div>
    <div class="col-xs-6">
        <div class="form-group">
            <label>Estado Boleta</label>
            <select name="estadoComprobante" class="form-control">
                <option value='0'>Selecciona Opci&oacute;n...</option> 
                <?php
                $EstadosComprobante = $servicios->ListarEstadosComprobante();
                foreach ($EstadosComprobante as $indice => $registro) {
                    if ($registro['codigo'] == $data['T_FacturacionEstadoComprobante_codigo']) {
                        echo "<option selected='" . (int) $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                    } else {
                        echo "<option value='" . (int) $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                    }
                }
                ?>
            </select>
        </div></div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</form>

<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
<script src="../../static/css/js/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>



<script type="text/javascript">
    $(function () {
        //Datemask dd/mm/yyyy
        $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Datemask2 mm/dd/yyyy
        $("#datemask2").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
        //Money Euro
        $("[data-mask]").inputmask();

        //Date range picker
        $('#reservation').daterangepicker();
        //Date range picker with time picker
        $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
        //Date range as a button
        $('#daterange-btn').daterangepicker(
                {
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                        'Last 7 Days': [moment().subtract('days', 6), moment()],
                        'Last 30 Days': [moment().subtract('days', 29), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                    },
                    startDate: moment().subtract('days', 29),
                    endDate: moment()
                },
        function (start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
        );

        //iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal',
            radioClass: 'iradio_minimal'
        });
        //Red color scheme for iCheck
        $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
            checkboxClass: 'icheckbox_minimal-red',
            radioClass: 'iradio_minimal-red'
        });
        //Flat red color scheme for iCheck
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
            checkboxClass: 'icheckbox_flat-red',
            radioClass: 'iradio_flat-red'
        });

        //Colorpicker
        $(".my-colorpicker1").colorpicker();
        //color picker with addon
        $(".my-colorpicker2").colorpicker();

        //Timepicker
        $(".timepicker").timepicker({
            showInputs: false
        });
    });
</script>
