<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
$servicios = new servicios();
} else {
    header('Location: /dashboard/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>
                <!-- Right side column. Contains the navbar and content of the page -->
                <aside class="right-side">



                    <section class="content-header">
                        <h1>
                            Dashboard
                            <small>Control panel</small>
                        </h1>

                        <ol class="breadcrumb">
                            <div class="headline text-center" id="time"></div>
                        </ol>
                    </section>

                    <section class="content">


                        <!--                        <div class="row">
                                                    <div class="col-md-12">
                                                     <div class="box box-info">
                                                            <div class="box-header">
                                                                <i class="fa fa-bullhorn"></i>
                                                                <h3 class="box-title">CLiente Naturales</h3>
                                                            </div> 
                                                            <div class="box-body">
                        
                        
                                                                <div class="row">
                                                                    <div class="col-lg-12 col-md-6 col-sm-6 col-xs-12  ">
                                                                    <div class="col-lg-4 col-xs-6">
                        
                                                                        <div class="small-box bg-aqua">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    <div class="headline text-center" id="time">
                        
                                                                                    </div> 
                                                                                </h3>
                                                                                <p>
                                                                                    Residenciales
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-bag"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                    <div class="col-lg-4 col-xs-6">
                                                                        <div class="small-box bg-green">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    53<sup style="font-size: 20px">%</sup>
                                                                                </h3>
                                                                                <p>
                                                                                    Negocios
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-stats-bars"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                    <div class="col-lg-4 col-xs-6">
                                                                        <div class="small-box bg-yellow">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    44
                                                                                </h3>
                                                                                <p>
                                                                                    Empresas
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-person-add"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                </div>
                        
                                                            </div> 
                                                        </div> 
                                                    </div> 
                                                    <div class="col-md-12">
                                                        <div class="box box-info">
                                                            <div class="box-header">
                                                                <i class="fa fa-bullhorn"></i>
                                                                <h3 class="box-title">Clientes Juridicos</h3>
                                                            </div> 
                                                            <div class="box-body">
                                                               
                                                                
                                                                 <div class="row">
                                                                    <div class="col-lg-12 col-md-6 col-sm-6 col-xs-12  ">
                                                                    <div class="col-lg-4 col-xs-6">
                        
                                                                        <div class="small-box bg-aqua">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    <div class="headline text-center" id="time">
                        
                                                                                    </div> 
                                                                                </h3>
                                                                                <p>
                                                                                    Residenciales
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-bag"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                    <div class="col-lg-4 col-xs-6">
                                                                        <div class="small-box bg-green">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    53<sup style="font-size: 20px">%</sup>
                                                                                </h3>
                                                                                <p>
                                                                                   Negocios
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-stats-bars"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                    <div class="col-lg-4 col-xs-6">
                                                                        <div class="small-box bg-yellow">
                                                                            <div class="inner">
                                                                                <h3>
                                                                                    44
                                                                                </h3>
                                                                                <p>
                                                                                    Empresas
                                                                                </p>
                                                                            </div>
                                                                            <div class="icon">
                                                                                <i class="ion ion-person-add"></i>
                                                                            </div>
                                                                            <a href="#" class="small-box-footer">
                                                                                More info <i class="fa fa-arrow-circle-right"></i>
                                                                            </a>
                                                                        </div>
                                                                    </div> 
                                                                </div>
                                                                
                                                            </div> 
                                                        </div> 
                                                    </div> 
                                                </div>-->
                        <h4 class="page-header">
                            <i class="fa fa-bar-chart-o"></i> Clientes Naturales
                        </h4>
                        <div class="row">
                            
                            
                            <div class="col-lg-4 col-xs-6">

                                <div class="small-box bg-aqua">
                                    <div class="inner">
                                        <h3>


                                            s
                                        </h3>
                                        <p>
                                            Residenciales
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-bag"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <div class="col-lg-4 col-xs-6">
                                <div class="small-box bg-green">
                                    <div class="inner">
                                        <h3>
                                            53<sup style="font-size: 20px">%</sup>
                                        </h3>
                                        <p>
                                            Negocios
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-stats-bars"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <div class="col-lg-4 col-xs-6">
                                <div class="small-box bg-yellow">
                                    <div class="inner">
                                        <h3>
                                            44
                                        </h3>
                                        <p>
                                            Empresas
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-person-add"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <!--                            <div class="col-lg-3 col-xs-6">
                                                            <div class="small-box bg-red">
                                                                <div class="inner">
                                                                    <h3>
                                                                        65
                                                                    </h3>
                                                                    <p>
                                                                        Unique Visitors
                                                                    </p>
                                                                </div>
                                                                <div class="icon">
                                                                    <i class="ion ion-pie-graph"></i>
                                                                </div>
                                                                <a href="#" class="small-box-footer">
                                                                    More info <i class="fa fa-arrow-circle-right"></i>
                                                                </a>
                                                            </div>
                                                        </div> -->
                        </div> 
                        <h4 class="page-header">
                            <i class="fa fa-bar-chart-o"></i> Clientes Juridicos
                            <!--<small>
                            Small boxes are used for viewing statistics. To create a small box use the class
                            <code>.small-box</code>
                            and mix & match using the
                            <code>bg-*</code>
                            classes.
                            </small>-->
                        </h4>
                        <div class="row">
                            <div class="col-lg-4 col-xs-6">
                                <div class="small-box bg-blue">
                                    <div class="inner">
                                        <h3>
                                            230
                                        </h3>
                                        <p>
                                            Residenciales
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-ios7-cart-outline"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <div class="col-lg-4 col-xs-6">
                                <div class="small-box bg-purple">
                                    <div class="inner">
                                        <h3>
                                            80<sup style="font-size: 20px">%</sup>
                                        </h3>
                                        <p>
                                            Negocios
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-ios7-briefcase-outline"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <div class="col-lg-4 col-xs-6">
                                <div class="small-box bg-teal">
                                    <div class="inner">
                                        <h3>
                                            14
                                        </h3>
                                        <p>
                                            Empresas
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-ios7-alarm-outline"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        More info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <!--                            <div class="col-lg-3 col-xs-6">
                                                            <div class="small-box bg-maroon">
                                                                <div class="inner">
                                                                    <h3>
                                                                        160
                                                                    </h3>
                                                                    <p>
                                                                        Products
                                                                    </p>
                                                                </div>
                                                                <div class="icon">
                                                                    <i class="ion ion-ios7-pricetag-outline"></i>
                                                                </div>
                                                                <a href="#" class="small-box-footer">
                                                                    More info <i class="fa fa-arrow-circle-right"></i>
                                                                </a>
                                                            </div>
                                                        </div> -->
                        </div>
                    </section> 
                </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
        <?php echo scripts(); ?>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function () {
                startTime();
                $(".center").center();
                $(window).resize(function () {
                    $(".center").center();
                });
            });
            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();
                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);
                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";
                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;
                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function () {
                    startTime()
                }, 500);
            }
            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }
            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function () {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>

