<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';

sec_session_start();
if (login_check($mysqli) == true) {
    $servicios = new servicios();
    // Add your protected page content here!
} else {
    header('Location: /'.AMBIENTE.'/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
     <body class="skin-blue pace-done fixed">
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <aside class="left-side sidebar-offcanvas">
                <?php echo menuLayout($_SESSION['username']); ?>
                <aside class="right-side">
                    <section class="content-header">
                        <h1>
                            Ordenes de Instalación en Curso
                        </h1>
                        <ol class="breadcrumb">
                            <div class="headline text-center" id="time"></div>
                        </ol>
                    </section>
                    <section class="content invoice">
                        <div class="row">
                            <iframe src="https://www.google.com/calendar/embed?src=<?php echo $_SESSION['email']?>&height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;ctz=America%2FLima" style=" border-width:0 " width="100%" height="600" frameborder="0" scrolling="no"></iframe>
                        </div> 
                    </section><!-- /.content -->
                </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
        <?php echo scripts(); ?>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        
    </body>
</html>
