<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';

sec_session_start();
if (login_check($mysqli) == true) {
    $servicios = new servicios();
    // Add your protected page content here!
} else {
    header('Location: /'.AMBIENTE.'/modulos/Admin/login.phtml');
}
?>
    <script type="text/javascript">
            var int=self.setInterval("refresh()",60000);
            function refresh()
            {
                    location.reload(true);
            }
    </script>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
     <body class="skin-blue pace-done fixed">
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <aside class="left-side sidebar-offcanvas">
                <?php echo menuLayout($_SESSION['username']); ?>
                <aside class="right-side">
                    <section class="content-header">
                        <h1>
                            Dashboard
                            <small>Control panel</small>
                        </h1>
                        <ol class="breadcrumb">
                            <div class="headline text-center" id="time"></div>
                        </ol>
                    </section>
                    <section class="content invoice">
                        <h4 class="page-header">
<!--                            <i class="fa fa-bar-chart-o"></i> Clientes Total-->
                        </h4>
                        <div class="row">
                            <div class="col-lg-6 col-xs-6">
                                <div class="small-box bg-aqua">
                                    <div class="inner">
                                        <?php 
                                        $resultado = 0;
                                        $ListarContratos = $servicios->TableroContratos(1, 0);
                                        foreach ($ListarContratos as $key => $value) {
                                            $resultado = $resultado + $value['Total'];
                                        }
                                        ?><h3 style="font-size: 3.5em">
                                        <?php echo $resultado ;?>
                                        </h3>
                                        <p style="font-size: 1.5em">
                                            Total De Contratos
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-stats-bars"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        Más info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                            <div class="col-lg-6 col-xs-6">
                                <div class="small-box bg-aqua">
                                    <div class="inner">
                                        <?php
                                        $ListarPedidos = $servicios->ListarPedidos();
                                        ?>
                                        <h3 style="font-size: 3.5em">
                                            <?php echo $ListarPedidos[0]['Total']; ?>
                                        </h3>
                                        <p style="font-size: 1.5em">
                                            Pedidos (Clientes Potenciales)
                                        </p>
                                    </div>
                                    <div class="icon">
                                        <i class="ion ion-person-add"></i>
                                    </div>
                                    <a href="#" class="small-box-footer">
                                        Más info <i class="fa fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div> 
                        </div>
                        <h4 class="page-header">
                            <i class="fa fa-bar-chart-o"></i> Contratos Activos
                        </h4>
                        <div class="row">
                            <?php
                             $contadorTwo = $servicios->contadorTablero(count($ListarContratos));
                            $resultadoResidencial=0;
                            foreach ($ListarContratos as $key => $value) {
                                 if($value['descripcion']=='Residencial' || $value['descripcion']=='Residencial-Fundador'){
                                     $resultadoResidencial = $resultadoResidencial + $value['Total'];
                                 }
                                }
                                ?>
                                <div class="col-lg-<?php echo $contadorTwo+1 ?> col-xs-6">
                                    <div class="small-box bg-blue">
                                        <div class="inner">
                                            <h3 style="font-size: 3.5em">
                                                <?php 
                                                echo $resultadoResidencial ?>
                                            </h3>
                                            <p style="font-size: 1.5em">
                                               Residencial
                                            </p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-ios7-briefcase-outline"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">
                                            Más info <i class="fa fa-arrow-circle-right"></i>
                                        </a>
                                    </div>
                                </div> 
                            <?php 
                            ?>
                            <?php
                            foreach ($ListarContratos as $key => $value) {
                                 if($value['descripcion']!='Residencial' && $value['descripcion']!='Residencial-Fundador'){
                                ?>
                                <div class="col-lg-<?php echo $contadorTwo+1 ?> col-xs-6">
                                    <div class="small-box bg-blue">
                                        <div class="inner">
                                            <h3 style="font-size: 3.5em">
                                                <?php 
                                                echo $value['Total'] ?>
                                            </h3>
                                            <p style="font-size: 1.5em">
                                                <?php echo $value['descripcion'] ?>
                                            </p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-ios7-briefcase-outline"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">
                                            Más info <i class="fa fa-arrow-circle-right"></i>
                                        </a>
                                    </div>
                                </div> 
                            <?php }}
                            ?>
                            
                        </div> 
                        <h4 class="page-header">
                            <i class="fa fa-bar-chart-o"></i> Ordenes
                        </h4>
                        <div class="row">
                            <?php
                            $ListarOrdenes = $servicios->ListarOrdenes(0);
                             $contadorThree = $servicios->contadorTablero(count($ListarOrdenes));
                            foreach ($ListarOrdenes as $key => $value) {
                                ?>
                                <div class="col-lg-<?php echo $contadorThree ?> col-xs-6">
                                    <div class="small-box bg-green-gradient">
                                        <div class="inner">
                                            <h3 style="font-size: 3.5em">
                                                <?php 
                                                echo $value['Total'] ?>
                                            </h3>
                                            <p style="font-size: 1.5em">
                                                <?php echo $value['descripcion'] ?>
                                            </p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-bag"></i>
                                        </div>
                                        <a href="calendario.phtml" class="small-box-footer">
                                            Más info <i class="fa fa-arrow-circle-right"></i>
                                        </a>
                                    </div>
                                </div> 
                            <?php }
                            ?>
                      </div>
                        
                        <h4 class="page-header">
                            <i class="fa fa-bar-chart-o"></i> Alarmas ONT
                        </h4>
                        <div class="row">
                            <?php
                            $result = file_get_contents('http://181.225.180.20/dashboard/scripts/ont.los');
                            if($result>0){
                               $color='bg-red'; 
                            }else{
                                $color='bg-yellow';
                            }
                                ?>
                                <div class="col-lg-6 col-xs-6">
                                    <div class="small-box <?php echo $color ?>">
                                        <div class="inner">
                                            <h3 style="font-size: 3.5em">
                                                <?php 
                                                echo $result ?>
                                            </h3>
                                            <p style="font-size: 1.5em">
                                                Alarma
                                            </p>
                                        </div>
                                        <div class="icon">
                                            <i class="ion ion-ios7-alarm-outline"></i>
                                        </div>
                                        <a href="#" class="small-box-footer">
                                            Más info <i class="fa fa-arrow-circle-right"></i>
                                        </a>
                                    </div>
                                </div> 
                      </div>
                    </section><!-- /.content -->
                </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
        <?php echo scripts(); ?>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function () {
                startTime();
                $(".center").center();
                $(window).resize(function () {
                    $(".center").center();
                });
            });
            /*  */
            function startTime()
            {
                var today = new Date();
                var h = today.getHours();
                var m = today.getMinutes();
                var s = today.getSeconds();
                // add a zero in front of numbers<10
                m = checkTime(m);
                s = checkTime(s);
                //Check for PM and AM
                var day_or_night = (h > 11) ? "PM" : "AM";
                //Convert to 12 hours system
                if (h > 12)
                    h -= 12;
                //Add time to the headline and update every 500 milliseconds
                $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                setTimeout(function () {
                    startTime()
                }, 500);
            }
            function checkTime(i)
            {
                if (i < 10)
                {
                    i = "0" + i;
                }
                return i;
            }
            /* CENTER ELEMENTS IN THE SCREEN */
            jQuery.fn.center = function () {
                this.css("position", "absolute");
                this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                        $(window).scrollTop()) - 30 + "px");
                this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                        $(window).scrollLeft()) + "px");
                return this;
            }
        </script>
    </body>
</html>
