<?php
include_once '../../includes/db_connect.php';
include_once '../../includes/functions.php';
sec_session_start();
if (login_check($mysqli) == true) {
    header('Location: /'.AMBIENTE.'/');
} else {
    $logged = 'fuera';
}
?>
<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>Dashboard |Moche </title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="../../static/css/css/AdminLTE.css" rel="stylesheet" type="text/css" />
        <script type="text/JavaScript" src="static/css/js/sha512.js"></script> 
        <script type="text/JavaScript" src="static/css/js/forms.js"></script> 
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="bg-black">
        <div class="form-box" id="login-box">
            <div class="header">Ingresar a su Cuenta</div>
            <?php if (isset($_GET['error'])) { ?>
                <div class="pad margin no-print">
                    <div class="alert alert-warning alert-dismissable">
                        <i class="fa fa-warning"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <b>Error al loguearse!</b>
                    </div>
                </div>
            <?php }
            ?> 
            <form action="controllers/process_login.php" method="post">
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="email" class="form-control" placeholder="Usuario ID" required/>
                    </div>
                    <div class="form-group">
                        <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña" required/>
                    </div>
                </div>
                <div class="footer">
                    <button type="submit" onclick="formhash(this.form, this.form.password);" name="login" value="Login" class="btn bg-olive btn-block">Ingresar aquí</button>

                </div>
            </form>
        </div>
        <?php echo scripts(); ?>
        <script src="../../static/css/js/forms.js" type="text/javascript"></script>
    </body>
</html>
