<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    // Add your protected page content here!
} else {
    header('Location: /' . AMBIENTE . '/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
    <body class="skin-blue pace-done fixed">

        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    <h1>
                        Registrar Nuevo Miembro
                    </h1>
                </section>
                <?php
                $error = filter_input(INPUT_GET, 'err', $filter = FILTER_SANITIZE_STRING);
                if ($_GET['me']) {
                    ?>
                    <div class="pad margin no-print">
                        <div class="box-body">
                            <div class="alert alert-success alert-dismissable">
                                <i class="fa fa-check"></i>
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <b> Usuario creado correctamente.</b>
                            </div>
                        </div><!-- /.box-body -->
                    </div>
                <?php }
                ?>
                <div class="pad margin no-print">
                    <div class="box-body">
                        <div class="alert alert-info alert-dismissable">
                            <i class="fa fa-info"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <ul>
                                <li>Los nombres de usuario pueden contener sólo dígitos , las letras mayúsculas y minúsculas y guiones bajos</li>
                                <li>Los correos electrónicos deben tener un formato de correo electrónico válida</li>
                                <li>Las contraseñas deben tener al menos 6 caracteres</li>
                                <li>Las contraseñas deben contener
                                    <ul>
                                        <li>Al menos una letra mayúscula (A..Z)</li>
                                        <li>Al menos una letra minúscula (a..z)</li>
                                        <li>Al menos un número de (0..9)</li>
                                    </ul>
                                </li>
                                <li>Su contraseña y la confirmación deben coincidir exactamente</li>
                            </ul>
                        </div>
                    </div><!-- /.box-body -->

                </div>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-12">
                            <!-- general form elements -->
                            <div class="box box-primary">
                                <div class="box-header">
                                    <h3 class="box-title">Registro</h3>
                                </div><!-- /.box-header -->
                                <!-- form start -->
                                <form action="controllers/register.inc.php" 
                                      method="post" 
                                      name="registration_form" role="form">
                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Nombre de Usuario</label>
                                            <input type="text" class="form-control"  name="username" id='username'  placeholder="Nombre">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Email</label>
                                            <input type="email"  name="email"   class="form-control" id="exampleInputEmail1" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Password</label>
                                            <input type="password" class="form-control" id="password" name="password"  placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Confirmar  el Password</label>
                                            <input type="password" id="confirmpwd" name="confirmpwd"  class="form-control"  placeholder="Repita el Password">
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Menu</label>

                                            <?php $menus = menuPadre();
                                            foreach ($menus as $key => $value) {
                                                ?>
                                                <div class="checkbox">
                                                    <label>
                                                        <input name="menu[]"  VALUE="<?php echo $value['id']; ?>"  type="checkbox"/>
                                                      <?php echo $value['descripcion']; ?>
                                                    </label>
                                                </div>

                                                <?php }
                                                ?>
                                            </div>
                                        </div><!-- /.box-body -->

                                        <div class="box-footer">
                                            <button value="Register" onclick="return regformhash(this.form,
                                                                this.form.username,
                                                                this.form.email,
                                                                this.form.password,
                                                                this.form.confirmpwd);" type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </form>
                                </div><!-- /.box -->




                            </div><!--/.col (left) -->

                        </div>   <!-- /.row -->
                    </section><!-- /.content -->
                </aside><!-- /.right-side -->
            </div><!-- ./wrapper -->


    <?php echo scripts(); ?>
        <!-- AdminLTE App -->
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <link href="../../static/css/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>

    </body>
</html>









