<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    if (isset($_GET['codigo']) and ! empty($_GET['codigo'])) {
        $servicios = new servicios();
        $Predio = $servicios->BuscarPredio($_GET['codigo']);
    } else {
        header('Location: /' . AMBIENTE . '/');
    }
} else {
    header('Location: /' . AMBIENTE . '/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
    <body class="skin-blue pace-done fixed">

        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>
                <!-- /.sidebar -->
            </aside>
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">

                <section class="content-header">
                    <h1 class="text-center">
                        Predios
                        <small>editar</small>
                    </h1>

                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">
                        <form action="controllers/register-predio.php" 
                              method="post" 
                              name="registration_form" role="form">
                            <!-- left column -->
                            <div class="col-md-6">
                                <!-- general form elements -->
                                <div class="box box-primary">

                                    <div class="box-body">
                                        <div class="form-group">
                                            <input name="codigo" type='hidden' value='<?php echo $_GET['codigo'] ?>'>
                                            <label for="exampleInputEmail1">Nombre</label>
                                            <input type="text" class="form-control" value="<?php echo $Predio['nombre'] ?>"  name="nombre" id='username'  placeholder="Nombre">
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Dirección</label>
                                            <input type="text"  name="direccion"  value="<?php echo $Predio['direccion'] ?>" class="form-control" id="exampleInputEmail1" placeholder="Dirección">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Numero de  Espacios</label>
                                            <input type="text" class="form-control" value="<?php echo $Predio['numeroEspacios'] ?>" id="password" name="numeroEspacios"  placeholder="Numero de  Espacios">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Capacidad de Splitter</label>
                                            <input type="text" id="confirmpwd" name="capacidadSplitter" value="<?php echo $Predio['capacidadSplitter'] ?>"  class="form-control"  placeholder="Capacidad de Splitter">
                                        </div>

                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Latitud</label>
                                            <input type="text" id="confirmpwd" name="latitud"  value="<?php echo $Predio['latitud'] ?>" class="form-control"  placeholder="Latitud">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Longitud</label>
                                            <input type="text" id="confirmpwd" name="longitud" value="<?php echo $Predio['longitud'] ?>" class="form-control"  placeholder="Longitud">
                                        </div>

                                    </div><!-- /.box-body -->
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->
                            <!-- left column -->
                            <div class="col-md-6">

                                <!-- general form elements -->
                                <div class="box box-primary">

                                    <div class="box-body">
                                        <div class="form-group">
                                            <label for="tieneONTenRecepcion">   Tiene ONT en Recepcion</label>
                                            <div class="checkbox">
                                                <label>
                                                    <input name="tieneONTenRecepcion" <?php if ($Predio['tieneONTenRecepcion'] == 1) { ?> checked <?php } ?>   type="checkbox"  />
                                                    Si
                                                </label>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label> Tipos De Predio</label>
                                            <select name="T_TipoPredio_codigo" class="form-control">
                                                <option value='0'>Selecciona Opci&oacute;n...</option> 
                                                <?php
                                                $ListarTiposPredio = $servicios->ListarTiposPredio();
                                                foreach ($ListarTiposPredio as $indice => $registro) {
                                                    if ($registro['codigo'] == $Predio['T_TipoPredio_codigo']) {
                                                        echo "<option selected='" . $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                    } else {
                                                        echo "<option value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label> Estado de Predio</label>
                                            <select name="T_EstadoPredio_codigo" class="form-control">
                                                <option value='0'>Selecciona Opci&oacute;n...</option> 
                                                <?php
                                                $ListarEstadosPredio = $servicios->ListarEstadosPredio();
                                                if ($Predio['T_EstadoPredio_codigo'] != 6) {
                                                    if ($Predio['T_EstadoPredio_codigo'] == 7) {
                                                        foreach ($ListarEstadosPredio as $indice => $registro) {
                                                            if ($registro['codigo'] != 8) {
                                                                if ($registro['codigo'] == $Predio['T_EstadoPredio_codigo']) {
                                                                    echo "<option selected='" . $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                                } else {
                                                                    echo "<option value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                                }
                                                            }
                                                        }
                                                    } else {
                                                        foreach ($ListarEstadosPredio as $indice => $registro) {
                                                            if ($registro['codigo'] != 8 && $registro['codigo'] != 7) {
                                                                if ($registro['codigo'] == $Predio['T_EstadoPredio_codigo']) {
                                                                    echo "<option selected='" . $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                                } else {
                                                                    echo "<option value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                                }
                                                            }
                                                        }
                                                    }
                                                } else {
                                                    foreach ($ListarEstadosPredio as $indice => $registro) {
                                                        if ($registro['codigo'] == $Predio['T_EstadoPredio_codigo']) {
                                                            echo "<option selected='" . $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                        } else {
                                                            echo "<option value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                        }
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label> Departamento</label>
                                            <select id="departamento" onChange='cargaContenido(this.id)' name="departamento" class="form-control">
                                                <option value='0'>Selecciona Opci&oacute;n...</option> 
                                                <?php
                                                $departamento = $servicios->ListarDepartamentos(0);
                                                foreach ($departamento as $indice => $registro) {
                                                    if ($registro['departamento'] == $Predio['departamento']) {
                                                        echo "<option  selected='" . $registro['departamento'] . "' value='" . $registro['departamento'] . "'>" . $registro['descripcion'] . "</option>";
                                                    } else {
                                                        echo "<option value='" . $registro['departamento'] . "'>" . $registro['descripcion'] . "</option>";
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="form-group" id="demoDer">
                                            <label> Provincia</label>
                                            <select  name="provincia" id="provincia" class="form-control">
                                                <option value="0">Selecciona opci&oacute;n...</option>
                                                <?php
                                                $ListarProvincias = $servicios->ListarProvincias($Predio['departamento'], 0);
                                                foreach ($ListarProvincias as $indice => $registro) {
                                                    if ($registro['provincia'] == $Predio['provincia']) {
                                                        echo "<option  selected='" . $registro['provincia'] . "' value='" . $registro['provincia'] . "'>" . $registro['descripcion'] . "</option>";
                                                    } else {
                                                        echo "<option value='" . $registro['provincia'] . "'>" . $registro['descripcion'] . "</option>";
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>
                                        <div class="form-group" id="demoProv">
                                            <label> Distrito</label>
                                            <select  name="distrito" id="distrito" class="form-control">
                                                <option value="0">Selecciona opci&oacute;n...</option>
                                                <?php
                                                $ListarDistritos = $servicios->ListarDistritos($Predio['departamento'], $Predio['provincia'], 0);
                                                foreach ($ListarDistritos as $indice => $registro) {
                                                    if ($registro['distrito'] == $Predio['distrito']) {
                                                        echo "<option  selected='" . $registro['distrito'] . "' value='" . $registro['distrito'] . "'>" . $registro['descripcion'] . "</option>";
                                                    } else {
                                                        echo "<option value='" . $registro['distrito'] . "'>" . $registro['descripcion'] . "</option>";
                                                    }
                                                }
                                                ?>
                                            </select>
                                        </div>

                                    </div><!-- /.box-body -->

                                    <div class="box-footer">
                                        <button value="Register" onclick="return regformhash(this.form,
                                                        this.form.nombreCompleto,
                                                        this.form.apellidoPaterno,
                                                        this.form.apellidoMaterno,
                                                        this.form.confirmpwd);" type="submit" class="btn btn-primary">Guardar</button>
                                        <a href="../../modulos/Predios/listar-predios.phtml"  class="btn btn-primary"><font color=white>Cancelar</font></a>
                                    </div>
                                    </form>
                                </div><!-- /.box -->




                            </div><!--/.col (left) -->
                    </div>   <!-- /.row -->
                </section><!-- /.content -->  
            </aside> 
        </div> 
        <?php echo scripts(); ?>

        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>

        <script src="../../static/css/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>

        <script src="../../static/css/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>

        <script src="../../static/css/js/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>

        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>

        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script src="../../static/css/js/select_dependiente.js" type="text/javascript"></script>
    </body>



</html>
