<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    $servicios = new servicios();
} else {
    header('Location: /'.AMBIENTE.'/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>

<html>
    <?php echo headLayout(); ?>
    <body class="skin-blue pace-done fixed">
        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>

                <!-- Right side column. Contains the navbar and content of the page -->
                <aside class="right-side">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1 class="text-center">Boletas</h1>
                    </section>
                    <!-- Main content -->
                    <section class="content invoice">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-xs-12">
                                <h2 class="page-header">
                                    <i class="fa fa-globe"></i> Lista de Boletas
                                    <div class="box-footer clearfix no-border">
<!--                                        <a href="cliente-juridico-insertar.php">  <button class="btn btn-default pull-right"><i class="fa fa-plus"></i>
                                                Agregar  </button></a>-->
                                    </div>
                                </h2>
                            </div><!-- /.col -->

                        </div>
                        <!-- info row -->
                        <div class="box">
                            <div class="box-body table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>numeroBoleta</th>
                                            <th>Cliente</th>
                                            <th>Documento</th>
                                            <th>Teléfonos</th>
                                            <th>distrito</th>
                                            <th>fechaEmision</th>
                                            <th>fechaVencimiento</th>
                                            <th>TotalaPagar</th>
                                            <th>mes</th>
                                            <th>Estado</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $ObtenerCabeceraFacturacion = $servicios->ObtenerCabeceraFacturacion(0, 0);
                                        foreach ($ObtenerCabeceraFacturacion as $indice => $registro) {
                                            $fechaEmision = date_create($registro['fechaEmision']);
                                            $fechaVencimiento = date_create($registro['fechaVencimiento']);
                                            ?>
                                            <tr>
                                                <td><a target='_blank' class='btn btn-app' href='controllers/pdf.php?codigo=<?php echo $registro['codigoContrato'] ?>&mes=<?php echo $registro['mes'] ?>' title='VER PDF'><?php echo $registro['numeroBoleta'] ?></a></td>
                                                <td><?php echo $registro['nombreCliente'] ?></td>
                                                <td><?php echo $registro['DocumentoIdentidad'] ?></td>
                                                <td><?php echo $registro['telefonoCelularContacto'] ?></td>
                                                <td><?php echo $registro['distrito'] ?></td>
                                                <td><?php echo date_format($fechaEmision, 'd/m/Y') ?></td>
                                                <td><?php echo date_format($fechaVencimiento, 'd/m/Y') ?></td>
                                                <td><?php echo $registro['TotalaPagar'] ?></td>
                                                <td><?php echo $servicios->obtenerUltimoDiaMesActual($registro['mes']) ?></td>
                                                <td><?php echo $registro['estado'] ?></td>
                                            </tr>
                                        <?php }
                                        ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>numeroBoleta</th>
                                            <th>Cliente</th>
                                            <th>Documento</th>
                                            <th>Teléfonos</th>
                                            <th>distrito</th>
                                            <th>fechaEmision</th>
                                            <th>fechaVencimiento</th>
                                            <th>TotalaPagar</th>
                                            <th>mes</th>
                                            <th>Estado</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div> 
                        </div>  
                        <!-- this row will not appear when printing -->
                        <div class="row no-print" >
                            <div class="col-xs-12">
                                <button class="btn btn-default" onclick="window.print();"><i class="fa fa-print"></i> Imprimir</button>
                                <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Generar PDF</button>
                            </div>
                        </div>
                    </section><!-- /.content -->
                </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
        <!-- AdminLTE App -->
<?php echo scripts(); ?>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <link href="../../static/css/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <script type="text/javascript">
                                    $(function () {
                                        $("#example1").dataTable();
                                        $('#example2').dataTable({
                                            "bPaginate": true,
                                            "bLengthChange": false,
                                            "mobFilter": false,
                                            "bSort": true,
                                            "bInfo": true,
                                            "bAutoWidth": false
                                        });
                                    });
        </script>
    </body>
</html>
