<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/functions_plan.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    $totEmp = new database();
} else {
    header('Location: /'.AMBIENTE.'/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>

<html>
    <?php echo headLayout(); ?>
     <body class="skin-blue pace-done fixed">
        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>

                <!-- Right side column. Contains the navbar and content of the page -->
                <aside class="right-side">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1 class="text-center">
                            Tiplos de Plan Clientes
                        </h1>
                    </section>
                    <!-- Main content -->
                    <section class="content invoice">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-xs-12">
                                <h2 class="page-header">
                                    <i class="fa fa-globe"></i> Lista Tiplos de Plan Clientes

                                </h2>
                            </div><!-- /.col -->
                        </div>
                        <!-- info row -->
                        <div class="box">
                            <div class="box-body table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Nombres y Apellidos</th>
                                            <th>telefono</th>
                                            <th>Tipo Cliente</th>
                                            <th>nombre_de_account</th>
                                            <th>Segundos X Tipo De Plan</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $ListarClientesPlanes = $totEmp->planesClientes();
                                        foreach ($ListarClientesPlanes as $indice => $rowPlanes) {
                                            ?>
                                            <tr>
                                                <td><?php echo utf8_encode($rowPlanes['persona']) ?></td>
                                                <td><?php echo $rowPlanes['telefono'] ?></td>
                                                <td><?php echo $rowPlanes['nombre_cliente_tipo_nombre'] ?></td>
                                                <td><?php echo $rowPlanes['nombre_de_account'] ?></td>
                                                <td><?php echo $rowPlanes['account_state'] ?></td>
                                            </tr>
                                            <?php }
                                            ?>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>Nombres y Apellidos</th>
                                                <th>telefono</th>
                                                <th>Tipo Cliente</th>
                                                <th>nombre_de_account</th>
                                                <th>Segundos X Tipo De Plan</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div> 
                            </div>  
                            <!-- this row will not appear when printing -->
                            <div class="row no-print">
                                <div class="col-xs-12">
                                    <button class="btn btn-default" onclick="window.print();"><i class="fa fa-print"></i> Imprimir</button>
                                    <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Generar PDF</button>
                                </div>
                            </div>
                        </section><!-- /.content -->
                    </aside><!-- /.right-side -->
            </div><!-- ./wrapper -->
    <?php echo scripts(); ?>
        <!-- AdminLTE App -->
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <link href="../../static/css/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <script type="text/javascript">
                                    $(function () {
                                        $("#example1").dataTable();
                                        $('#example2').dataTable({
                                            "bPaginate": true,
                                            "bLengthChange": false,
                                            "bFilter": false,
                                            "bSort": true,
                                            "bInfo": true,
                                            "bAutoWidth": false
                                        });
                                    });
        </script>
    </body>
</html>
