<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    $servicios = new servicios();
} else {
 header('Location: /'.AMBIENTE.'/modulos/Admin/login.phtml');}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
     <body class="skin-blue pace-done fixed">
        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>
                <!-- Right side column. Contains the navbar and content of the page -->
                <aside class="right-side">
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1  class="text-center">
                            Ordenes Nuevas
                        </h1>
                    </section>
                     <?php
                    if (isset($_GET['me'])):
                       $mensaje = mensajeGeneral($_GET['me'],'Orden');
                    endif;
                    echo $mensaje ;
                    ?>
                    <!-- Main content -->
                    <section class="content invoice">
                        <!-- title row -->
                        <div class="row">
                            <div class="col-xs-12">
                                <h2 class="page-header">
                                    <i class="fa fa-globe"></i> Lista de Ordenes Nuevas
                                    <div class="box-footer clearfix no-border">
<!--                                        <a href="cliente-juridico-insertar.php">  <button class="btn btn-default pull-right"><i class="fa fa-plus"></i>
                                                Agregar  </button></a>-->
                                    </div>
                                </h2>
                            </div><!-- /.col -->
                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Detalle de Orden</h4>
                                        </div>
                                        <div class="modal-body">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                            <!--<button type="button" class="btn btn-primary">Guardar Cambios</button>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- info row -->
                        <div class="box">

                            <div class="box-body table-responsive">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Codigo</th>
                                            <th>nombre Contacto Instalacion</th>
                                            <th>Teléfonos de Contacto</th>
                                            <th>correo Contacto Instalacion</th>
                                            <th>encargado</th>
                                            <th>fechaRegistro</th>
                                            <th>estado</th>
                                            <th>Detalle Instalacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $ListarOrdenesCliente = $servicios->ListarOrdenesCliente(0, 6);
                                        foreach ($ListarOrdenesCliente as $indice => $registro) {
//                                            if ($registro['T_EstadoOrdenCliente_codigo'] == 6 || $registro['T_EstadoOrdenCliente_codigo'] == 7 || $registro['T_EstadoOrdenCliente_codigo'] == 9) {
                                                $newDate = date("d/m/Y H:i:s", strtotime($registro['fechaRegistro']));
                                                ?>
                                                <tr>
                                                    <td><a class='btn btn-app' href='ordenes-cliente-editar.phtml?codigo=<?php echo $registro['codigo'] ?>' title='EDITAR'><i class='fa fa-edit'><i><?php echo $registro['codigo'] ?></i></i></a></td>
                                                    <td><?php echo $registro['nombreContactoInstalacion'] ?></td>
                                                    <td>Fijo [<?php echo $registro['telefonoFijoContactoInstalacion'] ?>] - Movil [<?php echo $registro['telefonoCelularContactoInstalacion'] ?>]</td>
                                                    <td><?php echo $registro['correoContactoInstalacion'] ?></td>
                                                    <td><?php echo $registro['encargado'] ?></td>
                                                    <td><?php echo $newDate ?></td>
                                                    <td><?php echo  $registro['nombreEstadoOrdenCliente'] ?></td>
                                                    <td> <button type="button" class="btn  btn-default btn-flat" data-toggle="modal"  data-target="#myModal" href="#" id="<?php echo $registro['codigo'] ?>">Detalle</button></td>
                                                </tr>
                                            <?php //}
                                        }
                                        ?>
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th>Codigo</th>
                                            <th>nombre Contacto Instalacion</th>
                                            <th>telefono Fijo</th>
                                            <th>correo Contacto Instalacion</th>
                                            <th>encargado</th>
                                            <th>fechaRegistro</th>
                                            <th>estado</th>
                                            <th>Detalle Instalacion</th>
                                        </tr>
                                    </tfoot>
                                </table>

                            </div> 
                        </div>  
                        <!-- this row will not appear when printing -->
                        <div class="row no-print" >
                            <div class="col-xs-12">
                                <button class="btn btn-default" onclick="window.print();"><i class="fa fa-print"></i> Imprimir</button>
                                <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Generar PDF</button>
                            </div>
                        </div>
                    </section><!-- /.content -->
                </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->
        <?php echo scripts(); ?>
        <!-- AdminLTE App -->
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <link href="../../static/css/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css"/>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
        <script type="text/javascript">
                                    $(function () {
                                        $("#example1").dataTable();
                                        $('#example2').dataTable({
                                            "bPaginate": true,
                                            "bLengthChange": false,
                                            "bFilter": false,
                                            "bSort": true,
                                            "bInfo": true,
                                            "bAutoWidth": false
                                        });
                                    });
        </script>
        <script type="text/javascript">
            $(function () {
//                $('.btn').click(function () {
                $(document).on('click', '.btn', function (e) {
                    var essay_id = $(this).attr('id');
                    $.ajax({
                        type: 'get',
                        url: '/<?php echo AMBIENTE ?>/modulos/Ordenes/controllers/detalle-orden.php', // in here you should put your query 
                        data: 'codigo=' + essay_id, // here you pass your id via ajax .
                        // in php you should use $_POST['post_id'] to get this value 
                        success: function (r)
                        {
                            // now you can show output in your modal 
                            $('#mymodal').show();  // put your modal id 
                            $('.modal-body').show().html(r);
                        }
                    });
                });
                $('#modal').on('hidden.bs.modal', function () {
                    $(this).removeData('bs.modal');
                });

            });
        </script>
    </body>
</html>
