<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    if (isset($_GET['codigo']) and ! empty($_GET['codigo'])) {
        $servicios = new servicios();
        $OrdenCliente = $servicios->BuscarOrdenCliente($_GET['codigo']);
        $ContratoNatural = $servicios->BuscarContratoNaturales($OrdenCliente["T_Contrato_codigo"]);
        $tipo = 'natural';
        if (!$ContratoNatural) {
            $tipo = 'juridico';
            $ContratoNatural = $servicios->BuscarContratoJuridicos($OrdenCliente["T_Contrato_codigo"]);
        }
    } else {
        header('Location: /' . AMBIENTE . '/');
    }
} else {
    header('Location: /' . AMBIENTE . '/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <link href="../../static/css/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
    <link href="../../static/css/css/timepicker/bootstrap-timepicker.min.css" rel="stylesheet"/>
    <?php echo headLayout(); ?>
    <body class="skin-blue pace-done fixed">
        <!-- header logo: style can be found in header.less -->
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <?php echo menuLayout($_SESSION['username']); ?>
                <!-- /.sidebar -->
            </aside>
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <section class="content-header">
                    <h1 class="text-center">
                        Orden Cliente
                        <small>editar</small>
                    </h1>
                    <?php
                    if (isset($_GET['me'])):
                        $mensaje = mensajeGeneral($_GET['me'], 'Orden');
                    endif;
                    echo $mensaje;
                    ?>
                </section>
                <!-- Main content -->
                <section class="content">
                    <div class="row">

                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <h2 class="page-header">
                                        &nbsp;&nbsp;&nbsp; Datos de Cliente
                                    </h2>
                                </div> 
                            </div>
                            <div class="col-sm-6 invoice-col">
                                <address>
                                    <?php if ($tipo == 'natural') { ?>
                                        <strong>Nombre:</strong> <?php echo $ContratoNatural['nombreCompleto'] . ', ' . $ContratoNatural['apellidoPaterno'] . ' ' . $ContratoNatural['apellidoMaterno'] ?><br>
                                        <strong>tipo Documento:</strong> <?php echo $ContratoNatural['descripcionTipoDocumento'] ?><br>
                                        <strong>Documento:</strong> <?php echo $ContratoNatural['documentoIdentidad'] ?><br>
                                    <?php } else { ?>
                                        <strong>RUC:</strong> <?php echo $ContratoNatural['numeroRUC'] ?><br>
                                        <strong>Nombre de Contacto:</strong> <?php echo $ContratoNatural['nombreContacto'] ?><br>
                                        <strong>Razón Social:</strong> <?php echo $ContratoNatural['razonSocial'] ?><br>
                                    <?php } ?>
                                    <strong>Celular:</strong> <?php echo $ContratoNatural['telefonoCelularContacto'] ?><br/>
                                    <strong>Telefono: </strong><?php echo $ContratoNatural['telefonoFijoContacto'] ?><br/>
                                </address>
                            </div> 
                            <div class="col-sm-6 invoice-col">
                                <address>
                                    <strong>Correo de Trabajo: </strong><?php echo $ContratoNatural['correoTrabajoContacto'] ?><br>
                                    <strong>Correo personal:</strong> <?php echo $ContratoNatural['correoPersonalContacto'] ?><br>
                                    <strong>Estado Cliente:</strong> <?php echo $ContratoNatural['descripcionEstadoCliente'] ?><br>
                                    <strong>Dirección del Predio:</strong> <?php echo $ContratoNatural['direccionExactaPredio'] ?><br/>
                                    <strong>Nombre del Predio:</strong> <?php echo $ContratoNatural['nombrePredio'] ?><br/>
                                </address>
                            </div>
                            <br>
                        </div><!--/.col (left) -->


                    </div>   <!-- /.row -->
                    <div class="row">
                        <div class="col-md-12">

                            <div class="nav-tabs-custom">
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#tab_1" data-toggle="tab">Detalle de Orden</a></li>
                                    <li><a href="#tab_2" data-toggle="tab">Detalle de Plan</a></li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane active" id="tab_1">
                                        <form action="controllers/register.orden.cliente.php" 
                                              method="post" 
                                              name="registration_form" role="form">
                                            <!-- left column -->
                                            <div class="box-body">
                                                <div class="form-group">
                                                    <input name="urlNavegacion" type='hidden' value='<?php
                                                    $urlNavegacion = $_SERVER['REQUEST_URI'];
                                                    echo $urlNavegacion
                                                    ?>'>
                                                    <input name="codigo" type='hidden' value='<?php echo $_GET['codigo'] ?>'>
                                                    <!--<input name="TipoEstadoOrdenCliente" type='hidden' value='<?php echo $_GET['TipoEstadoOrdenCliente'] ?>'>-->
                                                    <input name="T_Contrato_codigo" type='hidden' value='<?php echo $OrdenCliente['T_Contrato_codigo'] ?>'>

                                                    <label for="exampleInputEmail1">Nombre de Contacto de Instalacion</label>
                                                    <input type="text" class="form-control" value='<?php echo $OrdenCliente['nombreContactoInstalacion'] ?>' name="nombreContactoInstalacion" id='username'  placeholder="Nombre de Contacto de Instalacion">
                                                </div>

                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">Telefono Fijo Contacto Instalacion</label>
                                                    <input type="text"  name="telefonoFijoContactoInstalacion"   value='<?php echo $OrdenCliente['telefonoFijoContactoInstalacion'] ?>' class="form-control" id="exampleInputEmail1" placeholder="Telefono Fijo Contacto Instalacion">
                                                </div>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Telefono Celular Contacto Instalacion</label>
                                                    <input type="text" class="form-control" value='<?php echo $OrdenCliente['telefonoCelularContactoInstalacion'] ?>' id="password" name="telefonoCelularContactoInstalacion"  placeholder="Telefono Celular Contacto Instalacion">
                                                </div>
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Correo de Contacto de Instalacion</label>
                                                    <input type="text" id="confirmpwd" value='<?php echo $OrdenCliente['correoContactoInstalacion'] ?>' name="correoContactoInstalacion"  class="form-control"  placeholder="Correo de Contacto de Instalacion">
                                                </div>

                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Encargado</label>
                                                    <input type="text" id="confirmpwd" value='<?php echo $OrdenCliente['encargado'] ?>' name="encargado"  class="form-control"  placeholder="Encargado">
                                                </div>
                                                <!-- Date and time range -->
                                                <div class="form-group">
                                                    <label>Rango de fecha y Hora de Instalación:</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-clock-o"></i>
                                                        </div>
                                                        <input type="text" value='<?php echo $OrdenCliente['rangoFechaInstalacion'] ?>'  name="rangoFechaInstalacion" class="form-control pull-right" id="reservationtime"/>
                                                    </div><!-- /.input group -->
                                                </div><!-- /.form group -->


                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Obsevaciones</label>
                                                    <textarea class="form-control" name="observaciones"  rows="3" placeholder="observaciones"><?php echo $OrdenCliente['observaciones'] ?></textarea>
                                                </div>
                                                <div class="form-group">
                                                    <label> Estado de Orden</label>
                                                    <select name="T_EstadoOrdenCliente_codigo" class="form-control">
                                                        <option value='0'>Selecciona Opci&oacute;n...</option> 
                                                        <?php
                                                        $estadoOrdenesCliente = $servicios->ListarEstadosOrdenCliente();
                                                        foreach ($estadoOrdenesCliente as $indice => $registro) {
                                                            if ($registro['codigo'] == $OrdenCliente['T_EstadoOrdenCliente_codigo']) {
                                                                echo "<option selected='" . $registro['codigo'] . "' value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                            } else {
                                                                echo "<option value='" . $registro['codigo'] . "'>" . $registro['descripcion'] . "</option>";
                                                            }
                                                        }
                                                        ?>
                                                    </select>
                                                </div>


                                            </div><!-- /.box-body -->
                                            <div class="box-footer">
                                                <button value="Register" onclick="" type="submit" class="btn btn-primary">Guardar</button>
                                                <a href="../../modulos/Ordenes/ordenes-cliente.phtml"  class="btn btn-primary"><font color=white>Cancelar</font></a>
                                            </div>

                                        </form>
                                    </div> 
                                    <div class="tab-pane" id="tab_2">
                                        <form action="controllers/register.detalle.contrato.php" 
                                              method="post" 
                                              name="registration_form" role="form">
                                            <div class="box-body">
                                                <input name="urlNavegacion" type='hidden' value='<?php
                                                $urlNavegacion = $_SERVER['REQUEST_URI'];
                                                echo $urlNavegacion;
                                                ?>'>
                                                <input name="codigoContrato" type='hidden' value='<?php echo $OrdenCliente["T_Contrato_codigo"] ?>'>
                                                <div class="form-group">  
                                                    <div class="panel-group" id="accordion">
                                                        <?php
                                                        $PlanesServicio = $servicios->ListarPlanesServiciosPorPlan();
                                                        $detalleContrato = $servicios->ListarDetalleContrato($OrdenCliente["T_Contrato_codigo"]);
//                                                foreach ($PlanesServicio as $indice => $registro) {
                                                        foreach ($detalleContrato as $indice => $registro) {
                                                            $valor = $servicios->convert_number_to_words($registro['codigo']);
                                                            echo ' <div class="panel panel-info">
                                                    <div class="panel-heading">
                                                        <h4 class="panel-title">
                                                        <a data-toggle="collapse" data-parent="#accordion"
                                                          href="#accordion' . $valor . '">';
                                                            $data = $servicios->filter_by_value($detalleContrato, 'T_PlanServicio_codigo', $registro['codigo']);
                                                            if ($data) {
                                                                $fecha = date_create($data[0]['fechaEntrega']);
                                                                $fechaEntrega = date_format($fecha, 'd/m/Y');

                                                                echo ' <input name="planServicio[]"  value="' . $registro['codigo'] . '"  type="checkbox" checked  />';
                                                            } else {
                                                                echo ' <input name="planServicio[]" value="' . $registro['codigo'] . '"  type="checkbox"  />';
                                                                $fechaEntrega = '';
                                                            }
                                                            echo '&nbsp;&nbsp;&nbsp;&nbsp;<span class="text">' . $registro['nombrePlan'] . ' - ' . $registro['nombreServicio'] . '</span>';
                                                            echo '  </a>
                                                        </h4>
                                                    </div>';
                                                            echo ' <div id="accordion' . $valor . '" class="panel-collapse collapse">';
                                                            echo '     <div class="panel-body">';
                                                            echo ' <div class="form-group">
                                                                <label for="exampleInputEmail1">Costo de Instalacion </label>
                                                                <input type="text"  name="cargoInstalacion[' . $registro['codigo'] . ']" value="' . $data[0]['cargoInstalacion'] . '"   class="form-control" id="exampleInputEmail1" placeholder="Cargo de Instalacion">
                                                            </div>
                                                            <div class="form-group">
                                                                <label for="exampleInputEmail1">Ont Asignado</label>
                                                                <input type="text"  name="ontAsignado[' . $registro['codigo'] . ']" value="' . $data[0]['ontAsignado'] . '"   class="form-control" id="exampleInputEmail1" placeholder="Ont Asignado">
                                                            </div>
                                                             <div class="form-group">
                                                                <label for="exampleInputEmail1">Teléfono Voy Asignado</label>
                                                                <input type="text"  name="telefonoVoyAsignado[' . $registro['codigo'] . ']" value="' . $data[0]['telefonoVoyAsignado'] . '"   class="form-control" id="exampleInputEmail1" placeholder="Teléfono Voy Asignado">
                                                            </div>
                                                            <!-- Date dd/mm/yyyy -->
                                                            <div class="form-group">
                                                                <label>Fecha de Entrega:</label>
                                                                <div class="input-group">
                                                                    <div class="input-group-addon">
                                                                        <i class="fa fa-calendar"></i>
                                                                    </div>
                                                                    <input type="text" name="fechaEntrega[' . $registro['codigo'] . ']" value="' . $fechaEntrega . '" class="form-control" data-inputmask="' . "'" . 'alias' . "'" . ': ' . "'" . 'dd/mm/yyyy' . "'" . '" data-mask/>
                                                                </div>
                                                            </div>';
                                                            echo ' </div>
                                                    </div>
                                                </div>';
                                                        }
                                                        ?>
                                                    </div>
                                                </div>   
                                            </div><!-- /.box-body -->
                                            <div class="box-footer">
                                                <button value="Register"  type="submit" class="btn btn-primary">Guardar</button>
                                                <a href="../../modulos/Ordenes/ordenes-cliente.phtml"  class="btn btn-primary"><font color=white>Cancelar</font></a>
                                            </div>
                                        </form>
                                    </div> 
                                </div> 
                            </div> 
                        </div> 

                    </div> 






                </section><!-- /.content -->  
            </aside> 
        </div> 
        <?php echo scripts(); ?>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function () {
                //Datemask dd/mm/yyyy
                $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
                //Datemask2 mm/dd/yyyy
                $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
                //Money Euro
                $("[data-mask]").inputmask();

                //Date range picker
                $('#reservation').daterangepicker();
                //Date range picker with time picker
                $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 10, format: 'DD/MM/YYYY h:mm A'});
                //Date range as a button
                $('#daterange-btn').daterangepicker(
                        {
                            ranges: {
                                'Today': [moment(), moment()],
                                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                                'Last 7 Days': [moment().subtract('days', 6), moment()],
                                'Last 30 Days': [moment().subtract('days', 29), moment()],
                                'This Month': [moment().startOf('month'), moment().endOf('month')],
                                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                            },
                            startDate: moment().subtract('days', 29),
                            endDate: moment()
                        },
                function (start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                }
                );

                //iCheck for checkbox and radio inputs
                $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                    checkboxClass: 'icheckbox_minimal',
                    radioClass: 'iradio_minimal'
                });
                //Red color scheme for iCheck
                $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                    checkboxClass: 'icheckbox_minimal-red',
                    radioClass: 'iradio_minimal-red'
                });
                //Flat red color scheme for iCheck
                $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                    checkboxClass: 'icheckbox_flat-red',
                    radioClass: 'iradio_flat-red'
                });

                //Colorpicker
                $(".my-colorpicker1").colorpicker();
                //color picker with addon
                $(".my-colorpicker2").colorpicker();

                //Timepicker
                $(".timepicker").timepicker({
                    showInputs: false
                });
            });
        </script>
    </body>
</html>
