<?php
include_once '../../includes/register.inc.php';
include_once '../../includes/functions.php';
include_once '../../includes/services.php';
include_once '../../layout.php';
sec_session_start();
if (login_check($mysqli) == true) {
    $servicios = new servicios();
} else {
    header('Location: /' . AMBIENTE . '/modulos/Admin/login.phtml');
}
?>
<!DOCTYPE html>
<html>
    <?php echo headLayout(); ?>
    <body class="skin-blue pace-done fixed">
        <?php echo headerLayout($_SESSION['username']); ?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <aside class="left-side sidebar-offcanvas">
                <?php echo menuLayout($_SESSION['username']); ?>
            </aside>
            <aside class="right-side">
                
                <section class="content-header">
                    <h1 class="text-center">
                        <small>Crear </small>
                        Propuesta Comercial
                    </h1>
                    <?php
                    if (isset($_GET['me'])):
                        $mensaje = mensajeGeneral($_GET['me'], 'Propuesta');
                    endif;
                    echo $mensaje;
                    ?>
                </section>
                <section class="content">
                    <div class="row">
                        <form action="controllers/register.propuesta.comercial.php" 
                              method="POST" 
                              name="registration_form" role="form">
                            <div class="col-md-12">
                                <!-- general form elements -->
                                <div class="box box-primary">
                                    <div class="box-header">
                                        <h3 class="box-title">Cliente</h3>
                                    </div>
                                    <!-- form start -->
                                    <div class="row">
                                        <div class="box-body">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Razon Social</label>
                                                    <input type="hidden" value="<?php echo $_SESSION['user_id'] ?>" name="userId">
                                                    <input type="text" class="form-control"  name="razonSocial" id='username'  placeholder="razon Social">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <!-- Date dd/mm/yyyy -->
                                                <div class="form-group">
                                                    <label>Fecha:</label>
                                                    <div class="input-group">
                                                        <div class="input-group-addon">
                                                            <i class="fa fa-calendar"></i>
                                                        </div>
                                                        <input name="urlNavegacion" type='hidden' value='<?php
                                            $urlNavegacion = $_SERVER['REQUEST_URI'];
                                            echo $urlNavegacion
                                            ?>'>
                                                        <input type="text" name="fechaPropuesta" value='<?php
                                                        echo date("d/m/Y");
                                                        ?>' class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask/>
                                                    </div><!-- /.input group -->
                                                </div><!-- /.form group -->
                                            </div><!-- /.form group -->
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>RUC</label>
                                                    <input type="text"  name="numeroRUC"   class="form-control" id="exampleInputEmail1" placeholder="numeroRUC" required>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Contacto</label>
                                                    <input type="text" class="form-control" id="password" name="nombreContacto"  placeholder="nombre Contacto" required>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Teléfono</label>
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-phone"></i>
                                                    </div>
                                                    <input class="form-control" name="telefono" type="text" data-mask="" data-inputmask="'mask': ['999-999-999', '+099 99 99 9999[9]-9999']">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <label>Correo</label>
                                                <div class="input-group">
                                                    <span class="input-group-addon">
                                                        <i class="fa fa-envelope"></i>
                                                    </span>
                                                    <input class="form-control" name="correo" type="text" placeholder="Email" required>
                                                </div>
                                            </div>
                                            <div class="col-md-6">&nbsp;</div><div class="col-md-6">&nbsp;</div>
                                        </div><!-- /.box-body -->
                                    </div>
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->

                            <div class="col-md-12">
                                <!-- general form elements -->
                                <div class="box box-primary">
                                    <div class="box-header">
                                        <h3 class="box-title">Servicio</h3>
                                    </div>
                                    <!-- form start -->
                                    <div class="row">
                                        <div class="box-body">
                                            <div class="col-md-12">
                                                <div class="form-group">  
                                                    <div class="panel-group" id="accordion">

                                                        <div class="panel panel-info">
                                                            <div class="panel-heading">
                                                                <h4 class="panel-title">
                                                                    <a  data-toggle="collapse" data-parent="#accordion"
                                                                        href="#accordionTwo">
                                                                        <input id="check"  name="planServicio[]"   value="1"  type="checkbox"   />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp;<span class="text">INTERNET</span>
                                                                    </a>
                                                                </h4>
                                                            </div>
                                                            <div id="accordionTwo" class="panel-collapse collapse">
                                                                <div class="panel-body">
                                                                    <div class="form-group" id="demoDer">
                                                                        <label> Planes</label>
                                                                        <select  name="PlanInternet" onChange="pagoOnChange(this)" class="form-control">
                                                                            <option value="0">Selecciona opci&oacute;n...</option>
                                                                            <option  value="1" >&nbsp;&nbsp;&nbsp;&nbsp;Plan Negocios&nbsp;&nbsp;</option>
                                                                            <option  value="2">&nbsp;&nbsp;&nbsp;&nbsp;Plan Emprendedor&nbsp;&nbsp;&nbsp;&nbsp;</option>
                                                                            <option  value="3">&nbsp;&nbsp;&nbsp;&nbsp;Otros</option>
                                                                        </select>
                                                                    </div>
                                                                    <div style="display:none" id="ocultarPlanNegocio" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Precio</label>
                                                                            <input type="text" class="form-control" value="S/.500" name="precioPlanNegocios"  placeholder="nombre Contacto">
                                                                        </div>
                                                                    </div>
                                                                    <div style="display:none" id="ocultarPlanNegocioEmprendedor" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Precio</label>
                                                                            <input type="text" class="form-control" value="S/.350" name="precioPlanEmprendedor"  placeholder="nombre Contacto">
                                                                        </div>
                                                                    </div>
                                                                    <div style="display:none" id="ocultoOtroPlan" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Descripcion</label>
                                                                            <textarea class="form-control" placeholder="Descripcion Del otro Plan" rows="3" name="otroPlanInternet"></textarea>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="panel panel-info">
                                                            <div class="panel-heading">
                                                                <h4 class="panel-title">
                                                                    <a data-toggle="collapse" data-parent="#accordion"
                                                                       href="#accordionOne">
                                                                        <input name="planServicio[]"  value="2"  type="checkbox" />

                                                                        &nbsp;&nbsp;&nbsp;&nbsp;<span class="text">TELEFONO</span>
                                                                    </a>
                                                                </h4>
                                                            </div>
                                                            <div id="accordionOne" class="panel-collapse collapse">
                                                                <div class="panel-body">
                                                                    <div class="form-group" id="demoDer">
                                                                        <label> Servicio</label>
                                                                        <select  name="Tipotelefono" onChange="TelefonoServicio(this)" class="form-control">
                                                                            <option value="0">Selecciona opci&oacute;n...</option>
                                                                            <option value="1">Telefono nuevo</option>
                                                                            <option value="2">Portabilidad</option>
                                                                        </select>
                                                                    </div>
                                                                    <div style="display:none" id="ocultoPortabilidad" class="form-group">

                                                                        <div class="form-group">
                                                                            <label>Cantidad</label>
                                                                            <input type="text"  name="cantidanTelefonoPortabilidad" value=""   class="form-control" id="exampleInputEmail1" placeholder="Cantidad">
                                                                        </div>
                                                                        <div class="form-group">
                                                                            <label>numeros</label>
                                                                            <textarea class="form-control" placeholder="Numeros portables" rows="3" name="numerosTelefonoPortabilidad"></textarea>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-group" id="demoDer">
                                                                        <label> Planes</label>
                                                                        <select  name="PlanTelefono" onChange="TelefonoPlanes(this)" class="form-control">
                                                                            <option value="0">Selecciona opci&oacute;n...</option>
                                                                            <option value="1">&nbsp;&nbsp;&nbsp;&nbsp;Primario 8 canales&nbsp;&nbsp;&nbsp;&nbsp;</option>
                                                                            <option value="2">&nbsp;&nbsp;&nbsp;&nbsp;Primario 16 canales&nbsp;&nbsp;&nbsp;&nbsp;</option>
                                                                            <option value="3">&nbsp;&nbsp;&nbsp;&nbsp;Primario 32 canales&nbsp;&nbsp;&nbsp;&nbsp;</option>
                                                                            <option value="4">&nbsp;&nbsp;&nbsp;&nbsp;otros</option>
                                                                        </select>
                                                                    </div>
                                                                    <div style="display:none" id="ocultarPrimario8" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Precio</label>
                                                                            <input type="text" class="form-control" value="S/.200" name="precioPlanPrimario8"  placeholder="nombre Contacto">
                                                                        </div>
                                                                    </div>
                                                                    <div style="display:none" id="ocultarPrimario16" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Precio</label>
                                                                            <input type="text" class="form-control" value="S/.400" name="precioPlanPrimario16"  placeholder="nombre Contacto">
                                                                        </div>
                                                                    </div>
                                                                    <div style="display:none" id="ocultarPrimario32" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Precio</label>
                                                                            <input type="text" class="form-control" value="S/.600" name="precioPlanPrimario32"  placeholder="nombre Contacto">
                                                                        </div>
                                                                    </div>
                                                                    <div style="display:none" id="ocultoOtroServicioTelefono" class="form-group">
                                                                        <div class="form-group">
                                                                            <label>Descripcion</label>
                                                                            <textarea class="form-control" placeholder="Otro plan telefono" rows="3" name="otroPlanTelefono"></textarea>
                                                                        </div>
                                                                    </div>
                                                                    <label for="exampleInputEmail1">COSTO POR MINUTOS ADICIONALES</label>
                                                                    <div  class="form-group">
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                <label>Costo por minuto local onnet</label>
                                                                                <input type="text"  name="costoLocalOnnet" value="S/.0.000"   class="form-control" id="exampleInputEmail1" placeholder="Cargo de Instalacion">                                                                        </div>
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                <label>Costo por minuto local offnet</label>
                                                                                <input type="text"  name="costoLocalOffnet" value="S/.0.047"   class="form-control" id="exampleInputEmail1" placeholder="Cargo de Instalacion">                                                                        </div>
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                <label>Móviles cualquier operador</label>
                                                                                <input type="text"  name="movilesCualquier" value="S/.0.254"   class="form-control" id="exampleInputEmail1" placeholder="Cargo de Instalacion">                                                                        </div>
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                <label>Larga distancia fijo nacional (LDN)</label>
                                                                                <input type="text"  name=largaDistacia value="S/.0.300"   class="form-control" id="exampleInputEmail1" placeholder="Cargo de Instalacion">                                                                        </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>  
                                            </div><!-- /.form group -->
                                            <div class="col-md-12">&nbsp;</div>
                                        </div><!-- /.box-body -->
                                    </div>
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->
                            <div class="col-md-12">
                                <!-- general form elements -->
                                <div class="box box-primary">
                                    <div class="box-header">
                                        <h3 class="box-title">Condiciones</h3>
                                    </div>
                                    <!-- form start -->
                                    <div class="row">
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                <input name="condicionesServicio[]"  value="1"  type="checkbox" checked=""/>
                                                &nbsp;&nbsp;&nbsp;&nbsp;<span class="text">Generales</span>
                                            </div>
                                            <div class="col-md-4">
                                                <input name="condicionesServicio[]"  value="2"  type="checkbox" />
                                                &nbsp;&nbsp;&nbsp;&nbsp;<span class="text">Internet</span>
                                            </div>
                                            <div class="col-md-4">
                                                <input name="condicionesServicio[]"  value="3"  type="checkbox" />
                                                &nbsp;&nbsp;&nbsp;&nbsp;<span class="text">Teléfono</span>
                                            </div>
                                            <br>
                                            <div  id="ocultarCondicionesOtros" class="col-md-12">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">Otros</label>
                                                    <textarea class="form-control" placeholder="Otras condiciones" rows="3" name="otrasCondiciones"></textarea>
                                                </div>
                                            </div>
                                        </div><!-- /.box-body -->
                                    </div>
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->
                            <div class="col-md-12">
                                <!-- general form elements -->
                                <div class="box box-primary">
                                    <div class="box-header">
                                        <h3 class="box-title">Contacto</h3>
                                    </div>
                                    <!-- form start -->
                                    <div class="row">
                                        <div class="box-body">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Nombre</label>
                                                    <input type="text" class="form-control" value="<?php echo $_SESSION['username'] ?>" name="userName" >
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Teléfono</label>
                                                    <input type="text" class="form-control"  name="userPhone"  placeholder="Teléfono">
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>E-mail</label>
                                                    <input type="text" value="<?php echo $_SESSION['email'] ?>" class="form-control"  name="userEmail"  >
                                                </div>
                                            </div>
                                        </div><!-- /.box-body -->
                                    </div>
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->

                            <div class="col-md-12">
                                <!-- general form elements -->
                                <div class="box box-primary">

                                    <!-- form start -->
                                    <div class="row">
                                        <div class="box-body">
                                            <div class="col-md-12">
                                                <div class="box-footer">
                                                    <button class="btn btn-primary" type="submit" value="Register">Guardar</button>
                                                    <a class="btn btn-primary" href="../../modulos/Contratos/contratos.phtml">
                                                        <font color="white">Cancelar</font>
                                                    </a>
                                                </div>
                                            </div>

                                        </div><!-- /.box-body -->
                                    </div>
                                </div><!-- /.box -->
                            </div><!--/.col (left) -->
                        </form>
                    </div>   <!-- /.row -->
                </section><!-- /.content -->  
            </aside> 
        </div> 
        <?php echo scripts(); ?>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/colorpicker/bootstrap-colorpicker.min.js" type="text/javascript"></script>
        <script src="../../static/css/js/plugins/timepicker/bootstrap-timepicker.min.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/app.js" type="text/javascript"></script>
        <script src="../../static/css/js/AdminLTE/demo.js" type="text/javascript"></script>
        <script type="text/javascript">
                                                                            function TelefonoServicio(sel) {
                                                                                if (sel.value == "1") {
                                                                                    divT = document.getElementById("ocultoPortabilidad");
                                                                                    divT.style.display = "none";


                                                                                } else {
                                                                                    divT = document.getElementById("ocultoPortabilidad");
                                                                                    divT.style.display = "";
                                                                                }
                                                                            }

        </script>
        <script type="text/javascript">
            function pagoOnChange(sel) {
                if (sel.value == "1") {
                    divC = document.getElementById("ocultarPlanNegocio");
                    divC.style.display = "";

                    divT = document.getElementById("ocultarPlanNegocioEmprendedor");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultoOtroPlan");
                    divT.style.display = "none";

                } else if (sel.value == "2") {
                    divC = document.getElementById("ocultarPlanNegocioEmprendedor");
                    divC.style.display = "";

                    divT = document.getElementById("ocultarPlanNegocio");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultoOtroPlan");
                    divT.style.display = "none";

                } else {
                    divT = document.getElementById("ocultarPlanNegocio");
                    divT.style.display = "none";
                    divC = document.getElementById("ocultoOtroPlan");
                    divC.style.display = "";

                    divT = document.getElementById("ocultarPlanNegocioEmprendedor");
                    divT.style.display = "none";
                }
            }

        </script>

        <script type="text/javascript">
            function TelefonoPlanes(sel) {
                if (sel.value == "1") {
                    divC = document.getElementById("ocultarPrimario8");
                    divC.style.display = "";

                    divT = document.getElementById("ocultarPrimario16");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultarPrimario32");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultoOtroServicioTelefono");
                    divT.style.display = "none";

                } else if (sel.value == "2") {
                    divC = document.getElementById("ocultarPrimario8");
                    divC.style.display = "none";

                    divT = document.getElementById("ocultarPrimario16");
                    divT.style.display = "";
                    divT = document.getElementById("ocultarPrimario32");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultoOtroServicioTelefono");
                    divT.style.display = "none";

                } else if (sel.value == "3") {
                    divC = document.getElementById("ocultarPrimario8");
                    divC.style.display = "none";

                    divT = document.getElementById("ocultarPrimario16");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultarPrimario32");
                    divT.style.display = "";
                    divT = document.getElementById("ocultoOtroServicioTelefono");
                    divT.style.display = "none";

                } else {
                    divC = document.getElementById("ocultarPrimario8");
                    divC.style.display = "none";

                    divT = document.getElementById("ocultarPrimario16");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultarPrimario32");
                    divT.style.display = "none";
                    divT = document.getElementById("ocultoOtroServicioTelefono");
                    divT.style.display = "";
                }
            }

        </script><script type="text/javascript">
            $(function () {

                //Datemask dd/mm/yyyy
                $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
                //Datemask2 mm/dd/yyyy
                $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
                //Money Euro
                $("[data-mask]").inputmask();

                //Date range picker
                $('#reservation').daterangepicker();
                //Date range picker with time picker
                $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
                //Date range as a button
                $('#daterange-btn').daterangepicker(
                        {
                            ranges: {
                                'Today': [moment(), moment()],
                                'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                                'Last 7 Days': [moment().subtract('days', 6), moment()],
                                'Last 30 Days': [moment().subtract('days', 29), moment()],
                                'This Month': [moment().startOf('month'), moment().endOf('month')],
                                'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                            },
                            startDate: moment().subtract('days', 29),
                            endDate: moment()
                        },
                function (start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                }
                );

                //iCheck for checkbox and radio inputs
                $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                    checkboxClass: 'icheckbox_minimal',
                    radioClass: 'iradio_minimal'
                });
                //Red color scheme for iCheck
                $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                    checkboxClass: 'icheckbox_minimal-red',
                    radioClass: 'iradio_minimal-red'
                });
                //Flat red color scheme for iCheck
                $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                    checkboxClass: 'icheckbox_flat-red',
                    radioClass: 'iradio_flat-red'
                });

                //Colorpicker
                $(".my-colorpicker1").colorpicker();
                //color picker with addon
                $(".my-colorpicker2").colorpicker();

                //Timepicker
                $(".timepicker").timepicker({
                    showInputs: false
                });
            });
            $(document).ready(function () {
                $('#vinculo').click(function () {
                    $valor = $(this).attr('parametro'); // puedes remplazar "parametro" por le parametro que desees ya sea standar o personalizado
                    $('#codigoBoleta').val($valor);

                });
            });
        </script>
    </body>
</html>